### ISSUE TITLE
Add Icon

### ISSUE THREAD

**Issue by APakrohk** [vinceliuice/Qogir-icon-theme#1]
CMake : https://cmake.org/
VSCodium : https://github.com/VSCodium/vscodium
Krita : https://krita.org/en/
Discord : https://discordapp.com/
Ktorrent : https://kde.org/applications/internet/ktorrent/
Telegram Desktop : https://desktop.telegram.org
Persepolis Download Manager : https://persepolisdm.github.io/
OpenJDK Java : https://openjdk.java.net/
Hardinfo : https://github.com/lpereira/hardinfo

**Comment by vinceliuice** [comment]
No problem, I'll add those icons

**Comment by vinceliuice** [comment]
Added now
