### ISSUE TITLE
[Icon Request] DBeaver Community Edition

### ISSUE THREAD

**Issue by marcosins** [vinceliuice/Qogir-icon-theme#11]
Hello, I've recently discovered your icon theme and I love it, it would be nice if you could support this application (it's an SQL client).

---

DBeaver Community Edition :  [Website](https://dbeaver.io/) | [About](https://dbeaver.io/about/) | [Source Code](https://github.com/dbeaver/dbeaver)
AppIconName: `dbeaver`
![AppIcon](https://dbeaver.io/wp-content/uploads/2015/09/beaver-head.png)

**Comment by vinceliuice** [comment]
Added
