### ISSUE TITLE
[Icon request] Cinnamon Actions

### ISSUE THREAD

**Issue by ocobblepot** [vinceliuice/Qogir-icon-theme#125]
1. App name: Actions
2. App Github Homepage: https://github.com/linuxmint/cinnamon-spices-actions
3. App icon name: cs-actions

**Additional context**
hicolor theme icon

![cs-actions](https://github.com/vinceliuice/Qogir-icon-theme/assets/116648695/ba912df6-4e95-42b0-9a18-5c920703e439)

**Comment by vinceliuice** [comment]
Added
