### ISSUE TITLE
[Icon Request] Update Kate icon.

### ISSUE THREAD

**Issue by Kodehawa** [vinceliuice/Qogir-icon-theme#14]
The Kate icon has changed upstream [and it's no longer a simple notepad](https://kate-editor.org/). 

[Here's a blog post about it.](https://kate-editor.org/post/2020/2020-01-30-new-breeze-kate-icon/)

Would it be possible to update it to follow the new branding?

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
I updated this icon
