### ISSUE TITLE
[Icon Request] OpenTabletDriver

### ISSUE THREAD

**Issue by Kodehawa** [vinceliuice/Qogir-icon-theme#15]
If possible, could you add an icon for [OpenTabletDriver](https://github.com/InfinityGhost/OpenTabletDriver)?

Default icon:
![This is the default icon](https://user-images.githubusercontent.com/20606963/76707579-141e1280-66cf-11ea-937e-eda2d3245a45.png)

Thanks!

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
Added, but you need change the `OpenTabletDriver.desktop`
`Icon=/usr/share/OpenTabletDriver/Assets/otd.png` to `Icon=otd`

**Comment by Kodehawa** [comment]
> Added, but you need change the `OpenTabletDriver.desktop` :
> `Icon=/usr/share/OpenTabletDriver/Assets/otd.png` to `Icon=otd`

This has been fixed upstream by now, also thanks!
