### ISSUE TITLE
[Icon Request] CPU-X

### ISSUE THREAD

**Issue by Kodehawa** [vinceliuice/Qogir-icon-theme#16]
Could you please add an application icon for [CPU-X](https://github.com/X0rg/CPU-X)? It's a fairly popular software akin to CPU-Z on Windows. Would be cool to have a icon for it.

Default Icon:
![image](https://user-images.githubusercontent.com/20606963/76815607-dd362280-67dc-11ea-96a0-b8df996481f3.png)

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
Added!
