### ISSUE TITLE
Wrong icon on root drive on Dolphin when using Qogir-dark

### ISSUE THREAD

**Issue by Kodehawa** [vinceliuice/Qogir-icon-theme#17]
Title. 

Works fine when using normal Qogir.

Here's an screenshot of how it looks on Qogir-dark icons
![image](https://user-images.githubusercontent.com/20606963/77228340-5a5af200-6b65-11ea-86a6-bb3c369bb2e0.png)

Here's an screenshot on how it looks on Qogir (and how it should look)
![image](https://user-images.githubusercontent.com/20606963/77228345-6646b400-6b65-11ea-8856-8d1328e4f500.png)

**Comment by vinceliuice** [comment]
Is the last version still have this issue?

**Comment by Kodehawa** [comment]
![image](https://user-images.githubusercontent.com/20606963/86542361-2a044d00-bee3-11ea-993c-b559568fa0e0.png)

For me, yes. It's a fresh git clone aswell, and clean install.

**Comment by Kodehawa** [comment]
The issue becomes apparent once you enter the icon directory, go to the 16/devices
Compare both Qogir and Qogir-dark. Qogir-dark ends up with really odd icons on "devices". 

You can also see it on Cuttlefish, when you search "drive-harddisk-root" using Qogir-dark (then click on "see icon on other themes", it'll show you the icon is wrong).

Pleaaase fix :(
For now I fixed it myself by symlinking the Qogir's 16/devices folder to the Qogir-dark one.

**Comment by Kodehawa** [comment]
![image](https://user-images.githubusercontent.com/20606963/88702859-f24f8600-d0d9-11ea-8d4c-4ff9f14e3144.png)
This has been fixed. Closing.
