### ISSUE TITLE
[Icon Request] KWave

### ISSUE THREAD

**Issue by Kodehawa** [vinceliuice/Qogir-icon-theme#18]
Original icon: 
![image](https://user-images.githubusercontent.com/20606963/77241620-75fce180-6bd3-11ea-8b43-4beb3943218e.png)

[KWave is a sound editor and recorder for the KDE desktop.](https://kde.org/applications/multimedia/org.kde.kwave)

**Comment by vinceliuice** [comment]
No probblem!

**Comment by vinceliuice** [comment]
Added
