### ISSUE TITLE
[Icon Request] Basecamp

### ISSUE THREAD

**Issue by jamesponddotco** [vinceliuice/Qogir-icon-theme#20]
Hi,

Could make an icon for Basecamp, please?

I am aware that they do not have a Linux application at the moment, but you can still install their website as an application using GNOME Web, which is what I did.

**Their logo in several formats can be downloaded over here:**
https://basecamp.com/assets/about/press/basecamp-alt-logos-fe6580d323cd0cc406b9a273ae3beddb9fe6f96e8b12b6fd63b05713de281659.zip

Thank you in advance!

**Comment by jamesponddotco** [comment]
Built it myself using the `preferences-desktop-emoticons.svg` icon as a base since the application was bugging me, but I am not sure if this is the direction you would go with.

**Anyway, my attempt is over here:**
https://svgur.com/i/KG6.svg

**Comment by vinceliuice** [comment]
No problem!

**Comment by jamesponddotco** [comment]
@vinceliuice Looking forward to it! Feel free to use my attempt, if you like it.
