### ISSUE TITLE
[Icon Request] 

### ISSUE THREAD

**Issue by nguyenkien** [vinceliuice/Qogir-icon-theme#21]
**Insomnia designer**
This is official icon:
![designer](https://user-images.githubusercontent.com/1940081/81500890-3a42e600-92ff-11ea-8702-54b01a8b74b9.png)

**Jetbrains icon**
Please don't put black box inside colorful circle
This is my idea for it
![Screenshot from 2020-05-10 20-48-24](https://user-images.githubusercontent.com/1940081/81500960-b9d0b500-92ff-11ea-9c66-74dfbd16e725.png)

**Comment by vinceliuice** [comment]
Added
