### ISSUE TITLE
Error for inode-directory.svg

### ISSUE THREAD

**Issue by mahmutelmas06** [vinceliuice/Qogir-icon-theme#24]
inode-directory.svg gives some error that the linked source is not found.

I have checked which folder and  found that

16/mimetypes/inode-directory.svg
22/mimetypes/inode/directory

i have replaced from place/folder.svg with inode-directory.svg in 16 and 22 folder and issue fixed.

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by mahmutelmas06** [comment]
Problem seems fixed.
