### ISSUE TITLE
大佬我想问一下我的KDE为啥不能适配图标呀

### ISSUE THREAD

**Issue by kangseung** [vinceliuice/Qogir-icon-theme#25]
我观察了一下 比如文件夹无法适配，我看默认的文件夹图标名称就是folder，大佬的图标里叫default-folder 感觉是这里名字不匹配然后KDE桌面没有去找到这个图标路径。。

**Comment by vinceliuice** [comment]
你没用脚本安装吗，这些图标都做成链接了，相同图标只保留一个，其他的都是链接文件

**Comment by kangseung** [comment]
是用脚本安装的，系统是KUBUNTU 20.04 只有图标不好使，其他的都能用

**Comment by kangseung** [comment]
刚刚折腾了一下 发现好了，貌似我这个电脑上要先选全局样式，然后设置成默认，确定以后再选主题，然后去选图标 关了文件管理器再开开发现居然好了
