### ISSUE TITLE
Missing "Applications" icon on KDE config.

### ISSUE THREAD

**Issue by Kodehawa** [vinceliuice/Qogir-icon-theme#26]
![image](https://user-images.githubusercontent.com/20606963/86504908-6b361900-bd8c-11ea-8c8b-1ec11844dc4c.png)
This, pretty much. Latest git pulled and installed as the time of this post.

Thanks for reading!

**Comment by vinceliuice** [comment]
Application style icon?

**Comment by vinceliuice** [comment]
![图片](https://user-images.githubusercontent.com/7604295/86507144-5c8d4780-be08-11ea-9cde-ef9a0063cd12.png)

**Comment by vinceliuice** [comment]
I don't have this issue

**Comment by Kodehawa** [comment]
Seems to happen on Qogir-dark, Qogir is fine.

**Comment by Kodehawa** [comment]
That makes me remember that Qogir-dark is broken on KDE in other ways aswell (open dolphin and look at the drive icons when you select the Qogir-dark icon theme)

**Comment by vinceliuice** [comment]
![图片](https://user-images.githubusercontent.com/7604295/86523948-85641a00-bea6-11ea-8b1f-deb2fb174021.png)
Dark version It's also works fine on my desktop

**Comment by Kodehawa** [comment]
![image](https://user-images.githubusercontent.com/20606963/86542413-88c9c680-bee3-11ea-8c35-cb3a004f4663.png)
I set up a *fresh* virtual machine with a fresh install of KDE Neon Unstable and did a git clone of the Qogir-icon-theme repo, then installed it using bash install.sh. Same issue :(

**Comment by vinceliuice** [comment]
It's this issue only found on KDE Neon? is there any install error on this system?

**Comment by Kodehawa** [comment]
No. I could replicate it on any VM I created (KDE Neon, Ubuntu, Manjaro...)

My main system runs Arch.

Don't know why you don't have the issue, really. I only do a git clone of
this repo and run bash install.sh and the icon isn't there.

Are you in KDE 5.19.2? For me the icon you show is used in other place
(Default Applications) inside that menu.

**Comment by vinceliuice** [comment]
No I'm using KDE 5.18

**Comment by Kodehawa** [comment]
Oh. Yeah, this issue starting appearing on KDE 5.19

**Comment by Kodehawa** [comment]
In KDE 5.19 the new name is applications-all, and it's safe to copy the old icon to the new location.
cc: 
![image](https://user-images.githubusercontent.com/20606963/88357293-c4b0b880-cd38-11ea-8776-c3ba2dff592f.png)

**Comment by vinceliuice** [comment]
Thanks！ I‘ll fix this

**Comment by Kodehawa** [comment]
Just an FYI, this hasn't been fixed on any of the latest commits 👍🏻 
Thanks for the work on streamlining this for KDE though, it's looking better overall!

**Comment by vinceliuice** [comment]
Fogot this, I'll fix soon!

**Comment by Kodehawa** [comment]
Looks to be fixed, thanks you very much! 

Sorry for the nagging btw, I just love your theme and I wanna see it succeed!
It looks like it is going very well already, though hehe

Closing this as it's fixed on latest commit.
