### ISSUE TITLE
[Icon Request] Syncthing GTK, Veracrypt, Asymptote

### ISSUE THREAD

**Issue by etrmrh** [vinceliuice/Qogir-icon-theme#33]
Hello! I love your great work so far. I want to request custom icons for [Veracrypt](https://www.veracrypt.fr/code/VeraCrypt/), [Syncthing](https://syncthing.net/), and [Asymptote](https://asymptote.sourceforge.io/). Thank you!

**Comment by vinceliuice** [comment]
Added
