### ISSUE TITLE
Icon Request: elementary os actions icon

### ISSUE THREAD

**Issue by Chamrosh** [vinceliuice/Qogir-icon-theme#36]
[mail-move](https://github.com/elementary/icons/blob/master/actions/24/mail-move.svg)
[mail-inbox](https://github.com/elementary/icons/blob/master/places/16/mail-inbox.svg)
[mail-outbox](https://github.com/elementary/icons/blob/master/places/16/mail-outbox.svg)

![Screenshot from 2020-10-10 22 34 14](https://user-images.githubusercontent.com/10561726/95663173-c6289a80-0b49-11eb-8662-991e4465519a.jpg)

-----------------------------------------------

[image-crop.svg](https://github.com/elementary/icons/blob/master/actions/24/image-crop.svg)
[image-red-eye.svg](https://github.com/elementary/icons/blob/master/actions/24/image-red-eye.svg)
[object-straighten.svg](https://github.com/elementary/icons/blob/master/actions/24/object-straighten.svg)

![Screenshot from 2020-10-10 22 45 11](https://user-images.githubusercontent.com/10561726/95663243-68e11900-0b4a-11eb-8bd6-095bd617f5b3.png)

------------------------------------------------------

[edit-clear](https://github.com/elementary/icons/blob/master/actions/32/edit-clear.svg)

![Screenshot from 2020-10-10 23 03 35](https://user-images.githubusercontent.com/10561726/95663544-df7f1600-0b4c-11eb-9d2c-c20c248373bf.png)

--------------------------------------------

Proposal
I do not think the Bluetooth icon is very compatible with other icons!

![Screenshot from 2020-10-10 22 53 47](https://user-images.githubusercontent.com/10561726/95663361-7ea30e00-0b4b-11eb-80cf-30313651ebd0.png)

after edit:
![Screenshot from 2020-10-10 23 34 23](https://user-images.githubusercontent.com/10561726/95664055-2c64eb80-0b51-11eb-8a7a-e1417ded2ae8.png)

**Comment by lowski** [comment]
I'd also love to have such Bluetooth icon!

**Comment by vinceliuice** [comment]
Added
