### ISSUE TITLE
[Icon Request] 图标请求

### ISSUE THREAD

**Issue by liulitchi** [vinceliuice/Qogir-icon-theme#38]
现在我的三台电脑，全部装上了 Qogir 的图标和主题，其中一台是 ![OpenBSD](https://github.com/liulitchi/images/blob/master/openbsd68-mate-Qogir.png) 。整体上十分清爽，感谢大佬的辛苦工作。

图标美化工程是一个大项目，需要不断添加新图标，所以网友的反馈十分重要。我补充几个软件，有的可能已经更新了，那就直接忽略吧。

- Aegisub:  字幕编辑器
- Maxima / XMaxima / WxMaxima:  数学软件
- olive editor 视频编辑器
- putty: SSH 客户端
- ReText:  markdown 编辑器
- sigil: 电子书制作软件
- xournal: 笔记软件

另外，libreoffice 的图标似乎没有更新，也可能是我记错了。

**Comment by vinceliuice** [comment]
好的， 没问题！

**Comment by vinceliuice** [comment]
添加了
