### ISSUE TITLE
[Icon Request] Sequeler

### ISSUE THREAD

**Issue by lowski** [vinceliuice/Qogir-icon-theme#39]
Thank you for this icon pack, I love it!

There is one app that I'm using and it's missing the icon - [Sequeler](https://github.com/Alecaddd/sequeler). Would it be possible to add icons for it, please?

Thank you in advance!

**Comment by lowski** [comment]
I think something like for [sqlsudio](https://github.com/vinceliuice/Qogir-icon-theme/blob/master/src/scalable/apps/sqlitestudio.svg) but without feather inside could work :) .

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
Added

**Comment by lowski** [comment]
@vinceliuice thanks! I've just checked it and wanted to confirm if it's the right one - https://github.com/vinceliuice/Qogir-icon-theme/blob/master/src/scalable/apps/sequeler.svg (looks a bit different than others from this pack)

**Comment by vinceliuice** [comment]
I updated it

**Comment by lowski** [comment]
Thank you @vinceliuice, it looks great!
