### ISSUE TITLE
[Icon Request] Joplin

### ISSUE THREAD

**Issue by maeckha** [vinceliuice/Qogir-icon-theme#40]
Thank you for this icon pack, I love it!

There is one app that I'm using and it's missing the icon - [Joplin](https://joplinapp.org/). Would it be possible to add icons for it, please?

Thank you in advance!

**Comment by vinceliuice** [comment]
No problem!

**Comment by maeckha** [comment]
Thank you very much!
Do you want me to close the issue now or after you added the icon in one of the next updates?

**Comment by vinceliuice** [comment]
After I added this icon I'll close this

**Comment by vinceliuice** [comment]
Added

**Comment by maeckha** [comment]
Thanks!
