### ISSUE TITLE
Issues about folder / file manager icons

### ISSUE THREAD

**Issue by ilius** [vinceliuice/Qogir-icon-theme#41]
There are several issues or questions that I can find:

- `scalable/places/user-home.svg` is missing, there is `default-user-home.svg` instead which is rarely used in icon themes
    + Why is there `default-` prefixes in `places` folder? Shouldn't there be at least symbolic links to the standard names?
- `apps/file-manager.svg` looks more like what should be in `places/user-home.svg` (and looks better than `default-user-home.svg`), I think it needs to be replaced
- `apps/thunar.svg` is same as `places/default-folder.svg` but purple, why?
- I think `apps/thunar.svg` should be a symbolic link to `apps/file-manager.svg`
- It's nice to add `apps/caja.svg` and `apps/nautilus.svg` as symbolic links to `apps/file-manager.svg`

**Comment by vinceliuice** [comment]
![Screenshot from 2020-11-30 14-03-34](https://user-images.githubusercontent.com/7604295/100574389-e0465400-3314-11eb-842e-da85a7c783b2.png)
I checked user-home.svg is not missing

**Comment by ilius** [comment]
I see, so it's linked to `default-user-home.svg` on installation (I didn't install it)
I still think [apps/file-manager.svg](https://github.com/vinceliuice/Qogir-icon-theme/blob/master/src/scalable/apps/file-manager.svg) is a much better icon for `user-home.svg`
