### ISSUE TITLE
Icon Request 图标请求

### ISSUE THREAD

**Issue by liulitchi** [vinceliuice/Qogir-icon-theme#42]
我又来了，申请补充几个新图标：

- LMMS （影音）： mid 文件编辑器
- reaper ：音频编辑器，似乎缺乏高分辨率图标
- VSCodium:  vscode 复刻，缺乏高分辨率图标
- Calibre: 图标已有，但是它的三个辅助功能 `LRF Viewer`、`E-Book Viewer` 和 `E-Book  Editor` 需要补充。
- musescore：音乐类，打谱软件
- stellarium:  天文类软件，查看星图
- GNU Octave: 数学类软件， Matlab 替代
- gtranslator : po文件编辑器，类似 poedit 的翻译软件。

此外，还有几个文件名标识，可以补充一下：

- md  Markdown 文件
- c 
- srt / ass ：视频的字幕文件
- rs： Rust 语言代码文件

**Comment by vinceliuice** [comment]
没问题！
