### ISSUE TITLE
[Icon Request] Beekeeper studio

### ISSUE THREAD

**Issue by nguyenkien** [vinceliuice/Qogir-icon-theme#45]
You can find original icon here https://github.com/beekeeper-studio/beekeeper-studio/tree/master/public/icons/png

![preview](https://github.com/beekeeper-studio/beekeeper-studio/raw/master/public/icons/png/96x96.png)

**Comment by nguyenkien** [comment]
They have svg icon here: https://github.com/beekeeper-studio/beekeeper-studio/blob/master/src/assets/logo.svg

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
Added
