### ISSUE TITLE
Add symbolic links for xfce 4.16 new rDNS named icon

### ISSUE THREAD

**Issue by marcosins** [vinceliuice/Qogir-icon-theme#46]
In Xfce 4.16, app icon names have changed to follow a rDNS naming schema resulting in Qogir icons not appearing where they should.

Resources:
- Wiki with old/new names https://wiki.xfce.org/releng/4.16/icons_rdns_naming_for_icons
- Same issue for daniruiz/flat-remix#165
- xfce 4.16 announcement https://xfce.org/about/news/?post=1608595200

Thanks for your time creating this awesome theme.

**Comment by vinceliuice** [comment]
No problem! I'll fix that

**Comment by marcosins** [comment]
I sea you commited https://github.com/vinceliuice/Qogir-icon-theme/commit/2944d3df0345fe5935875d31b3e28bb6ed73d722
Thanks for your quick response to this!
