### ISSUE TITLE
[Request] Missing Icons

### ISSUE THREAD

**Issue by btd1337** [vinceliuice/Qogir-icon-theme#49]
- [ ] **Go For It!**
Comment=A stylish to-do list with built-in productivity timer
Icon=com.github.jmoerman.go-for-it
[Icon Link](https://github.com/JMoerman/Go-For-It/blob/master/data/icons/128x128/apps/go-for-it.svg)

- [ ] **Notes-Up**
Comment=Your markdown notebook
Icon=com.github.philip-scott.notes-up
[Icon Link](https://github.com/Philip-Scott/Notes-up/blob/master/data/icons/64/com.github.philip-scott.notes-up.svg)

- [ ] **GameHub**
Comment=All your games in one place
Icon=com.github.tkashkin.gamehub
[Icon Link](https://github.com/tkashkin/GameHub/blob/master/data/icon/128.svg)

- [ ] **Go For It!**
Comment=A stylish to-do list with built-in productivity timer
Icon=com.github.jmoerman.go-for-it
[Icon Link](https://github.com/JMoerman/Go-For-It/blob/master/data/icons/128x128/apps/go-for-it.svg)

- [ ] **Flowblade Movie Editor**
Comment=Edit media to create movies
Icon=io.github.jliljebl.Flowblade
[Icon Link](https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/Flowblade/res/img/flowbladeappicon.png)

- [ ] **OpenJDK Java 15**
Comment=OpenJDK Java 15
Icon=java15-openjdk
[Icon Link]()

- [ ] **Mars**
Comment=An IDE for programming in MIPS assembly language
Icon=mars-mips
[Icon Link](https://github.com/thomasrussellmurphy/MARS_Assembler/blob/master/images/mars.ico)

- [ ] **Micro**
Comment=Edit text files in a terminal
Icon=micro
[Icon Link](https://github.com/zyedidia/micro/blob/master/assets/micro-logo-mark.svg)

- [ ] **Modelio**
Comment=The opensource modeling environment
Icon=modelio
[Icon Link](https://github.com/ModelioOpenSource/Modelio/blob/master/products/icons/modelio.ico)

- [ ] **TablePlus**
Comment=Modern, native, and friendly GUI tool for relational databases (Alpha)
Icon=tableplus
[Icon Link](tableplus)

- [ ] **VStudio**
Comment=Database Tool
Icon=vstudio
[Icon Link](https://is4-ssl.mzstatic.com/image/thumb/Purple124/v4/c2/b7/c1/c2b7c161-8d26-7463-29e8-197f78fadbcf/Icon.png/230x0w.png)

- [ ] **Web Apps**
Comment=Run websites as if they were apps
Icon=webapp-manager
[Icon Link](https://github.com/linuxmint/webapp-manager/blob/master/usr/share/icons/hicolor/scalable/apps/webapp-manager.svg)

---

Generated by [icons-missing-script](https://github.com/btd1337/icons-missing-script)

**Comment by vinceliuice** [comment]
Added
