### ISSUE TITLE
Suggestion mimetype icon for Gameboy roms

### ISSUE THREAD

**Issue by luisrguerra** [vinceliuice/Qogir-icon-theme#51]
I made this mimetype icon for ".gb" file (application-x-gameboy-rom). ".gb" is only used for Gameboy games files (rom)
[https://fileinfo.com/extension/gb](https://fileinfo.com/extension/gb) 
PNG:
![application-x-gameboy-rom](https://user-images.githubusercontent.com/31783838/114312048-a279e900-9ac7-11eb-8747-edff0cc2aa50.png)

SVG vector:
![application-x-gameboy-rom](https://svgshare.com/i/W4q.svg)

some references:
![113953253-c8646c80-97ed-11eb-9620-b9000e1cf7a7](https://user-images.githubusercontent.com/31783838/114312199-3946a580-9ac8-11eb-9b24-f4c0deb2da3a.jpg)
![113953260-ca2e3000-97ed-11eb-849a-1e384ea78da9](https://user-images.githubusercontent.com/31783838/114312202-3a77d280-9ac8-11eb-92f6-1f06ad2021a1.jpg)

**Comment by luisrguerra** [comment]
Gameboy Color application-x-gameboy-color-rom (".gbc")
[https://fileinfo.com/extension/gbc](https://fileinfo.com/extension/gbc)

PNG:
![application-x-gameboy-color-rom](https://user-images.githubusercontent.com/31783838/114317430-73bb3d00-9ade-11eb-926b-9c0aee4aca86.png)

SVG Vector:
![application-x-gameboy-color-rom](https://svgshare.com/i/W4r.svg)

**Comment by vinceliuice** [comment]
Added
