### ISSUE TITLE
Broken symlink using install.sh

### ISSUE THREAD

**Issue by mjkalyan** [vinceliuice/Qogir-icon-theme#57]
After installing with install.sh, it appears the Aegisub icon is missing, which breaks a symlink.

i.e. `/usr/share/icons/Qogir/scalable/apps/org.aegisub.Aegisub.svg` points to `/usr/share/icons/Qogir/scalable/apps/aegisub.svg` which does not exist.

**Comment by vinceliuice** [comment]
![Screenshot from 2021-07-12 09-36-55](https://user-images.githubusercontent.com/7604295/125218078-b7e3f680-e2f4-11eb-982c-69e1fd4fddf4.png)

**Comment by vinceliuice** [comment]
Reinstall it
