### ISSUE TITLE
Request for Pacstall Support

### ISSUE THREAD

**Issue by wizard-28** [vinceliuice/Qogir-icon-theme#67]
[Pacstall](https://github.com/pacstall/pacstall) is a community-driven AUR-like package manager for Ubuntu. We have an ongoing [pull request](https://github.com/pacstall/pacstall-programs/pull/561) to add Qogir-icon-theme to our repository.

Would you like to maintain the pacscript (similar to a PKGBUILD) yourself? We can maintain it for you if you decide not to.

**Comment by wizard-28** [comment]
1 week has passed, so we would have to merge the pull request now. You can still request to maintain the script later on.

**Comment by vinceliuice** [comment]
That would be great you can maintain the pacscript for me, I actually don't know aboult it

**Comment by wizard-28** [comment]
Should I make a PR to your repository adding the instructions to the README about using Pacstall to install `qougir-icon-theme-bin` for Debian/Ubuntu users?

**Comment by vinceliuice** [comment]
Yes, that'll be great!
