### ISSUE TITLE
would it be possible to add EndeavourOS to the distributor icons?

### ISSUE THREAD

**Issue by killajoe** [vinceliuice/Qogir-icon-theme#73]
As we will go to use Qogir icons soon we would like to have EndeavourOS in the list of distributor icons.
I can provide a logo if needed.

**Comment by vinceliuice** [comment]
No problem!

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/endeavouros-theming/blob/master/endeavouros.svg
could be useful ? 
we have also this one: 
https://github.com/endeavouros-team/PKGBUILDS/blob/master/eos-qogir-icons/start-here-symbolic.svg

**Comment by vinceliuice** [comment]
Yes! I update it now

**Comment by killajoe** [comment]
thanks! 
This set is awesome!

**Comment by vinceliuice** [comment]
You are welcome!
