### ISSUE TITLE
mpv icon color

### ISSUE THREAD

**Issue by fn-ix** [vinceliuice/Qogir-icon-theme#74]
Hi! The Qogir icon for mpv is green while the signature color of mpv is [purple](https://mpv.io/); could you, please, change the hue of the Qogir mpv icon to match that of its native icon?
![image](https://user-images.githubusercontent.com/16854594/160225569-be9a5fe0-99e2-4017-8ad4-471af471a86f.png)

**Comment by vinceliuice** [comment]
No problem!

**Comment by Alexmelman88** [comment]
Hi guys, this issue can be closed. PR 89e6616f7bd03edce9d245b7da5b89b66a6a2ad4
